"""Adicionar profile_image_file como nullable

Revision ID: 34de796e96da
Revises: ff64a2793cac
Create Date: 2025-05-29 23:20:25.415671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34de796e96da'
down_revision = 'ff64a2793cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image_file', sa.String(length=100), server_default='default.jpg', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_image_file')

    # ### end Alembic commands ###
